{% set version = "2.1.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-repo
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/repo_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/repo/repo_{{ version }}.tar.gz
  sha256: c9910453465c1ec3a899b16596a9f2b30187045cc5b86bc2ad44af79869aed8d

build:
  merge_build_host: True  # [win]
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-digest
  run:
    - r-base
    - r-digest

test:
  commands:
    - $R -e "library('repo')"           # [not win]
    - "\"%R%\" -e \"library('repo')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=repo
  license: GPL-3.0-only
  summary: A data manager meant to avoid manual storage/retrieval of data to/from the file system.
    It builds one (or more) centralized repository where R objects are stored with rich
    annotations, including corresponding code chunks, and easily searched and retrieved.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: repo
# Type: Package
# Title: A Data-Centered Data Flow Manager
# Version: 2.1.3
# Date: 2018-5-4
# Author: Francesco Napolitano <franapoli@gmail.com>
# Maintainer: Francesco Napolitano <franapoli@gmail.com>
# Description: A data manager meant to avoid manual storage/retrieval of data to/from the file system. It builds one (or more) centralized repository where R objects are stored with rich annotations, including corresponding code chunks, and easily searched and retrieved.
# License: GPL-3
# Imports: digest, tools
# Suggests: igraph, knitr, shiny, testthat
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-05-16 16:14:32 UTC; ciccio
# Repository: CRAN
# Date/Publication: 2018-05-16 17:08:57 UTC
